InterviewOfOneSoftLimited/Models/PersonInfo.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InterviewOfOneSoftLimited.Models
{
    public class PersonInfo
    {
        [Key]
        public int PersonId { get; set; }

        [Required(ErrorMessage = "Must fill up name!")]
        [MaxLength(32)]
        public string Name { get; set; }

        [Required(ErrorMessage ="Select a country!")]
        [ForeignKey("Country")]
        public int CountryId { get; set; }

        [Required(ErrorMessage = "Select a city!")]
        [ForeignKey("City")]
        public int CityId { get; set; }
        
        [Required(ErrorMessage = "Must fill up date of birth!")]
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:dd MMM yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Resume not show and file must be pdf or doc!")]
        public string Resume { get; set; }


        //Navigation 
        public virtual Country Country { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<LanguageDetail> LanguageDetails { get; set; }
    }
}

InterviewOfOneSoftLimited/Models/ViewModel/PersonInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InterviewOfOneSoftLimited.Models.ViewModel
{
    public class PersonInfoViewModel
    {
        [Key]
        public int PersonId { get; set; }

        [Required(ErrorMessage = "Must fill up name!")]
        [MaxLength(32)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Select a country!")]
        [ForeignKey("Country")]
        public int CountryId { get; set; }

        [Required(ErrorMessage = "Select a city!")]
        [ForeignKey("City")]
        public int CityId { get; set; }
        
        [Required(ErrorMessage = "Must fill up date of birth!")]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Resume not show and file must be pdf or doc!")]
        public HttpPostedFileBase Resume { get; set; }

        [Required(ErrorMessage = "Select one or more language!")]
        public List<Language> Languages { get; set; }
        
        public PersonInfoViewModel()
        {
            this.Languages = new List<Language>();
        }
    }


}

InterviewOfOneSoftLimited/Controllers/PersonInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InterviewOfOneSoftLimited.Models;
using InterviewOfOneSoftLimited.Models.ViewModel;

namespace InterviewOfOneSoftLimited.Controllers
{
    public class PersonInfoController : Controller
    {
        private InterviewDbContext db = new InterviewDbContext();
        
        public ActionResult Index()
        {
            var personInfos = db.PersonInfos.Include(p => p.City).Include(p => p.Country).Include(p =>p.LanguageDetails).ToList();
            return View(personInfos);
        }

        public ActionResult Details(int? id)
        {
            PersonInfo personInfo = db.PersonInfos.Find(id);
            return View(personInfo);
        }
        public JsonResult GetEmps(string CountryId)
        {
            int id = Convert.ToInt32(CountryId);
            var data = db.Cities.Where(e => e.CountryId ==id ).Select(e => new { e.CityId, e.CityName }).ToList();
            return Json(data, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Create()
        {
            ViewBag.Country = db.Countries.ToList();
            ViewBag.CityId = new SelectList(db.Cities.ToList(), "CityId", "CityName");
            ViewBag.CountryId = new SelectList(db.Countries.ToList(), "CountryId", "CountryName");
            List<Language> lang = new List<Language>();
             lang = db.Languages.ToList();
            ViewBag.LanguageDetail = lang;
            PersonInfoViewModel model = new PersonInfoViewModel();
            foreach (var l in lang)
            {
                model.Languages.Add(new Language { LanguageId=l.LanguageId,LanguageName=l.LanguageName,IsSeleted=false});
            }
            return View(model);
        }
        
        [HttpPost]
        public ActionResult Create(PersonInfoViewModel personInfo,string hobbies)
        {
            List<Language> lang = new List<Language>();
            lang = db.Languages.ToList();
            ViewBag.LanguageDetail = lang;

            PersonInfo person = new PersonInfo();
            LanguageDetail languageDetail = new LanguageDetail();
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (personInfo.Resume.ContentLength > 0)
                {
                    fileName = Path.GetFileNameWithoutExtension(personInfo.Resume.FileName);
                    string extension = Path.GetExtension(personInfo.Resume.FileName);
                    fileName = fileName +"_"+ DateTime.Now.ToString("yymmssfff") + extension;
                    string filePath = Path.Combine(Server.MapPath("~/Images"), fileName);
                    personInfo.Resume.SaveAs(filePath);
                }
                person.Name = personInfo.Name;
                person.CountryId = personInfo.CountryId;
                person.CityId = personInfo.CityId;
                person.DateOfBirth = personInfo.DateOfBirth;
                person.Resume = fileName;
                db.PersonInfos.Add(person);
                db.SaveChanges();

                hobbies= hobbies + ",";
                string s = "";
                foreach (var i in hobbies)
                {
                    if (i == ',')
                    {
                        int id = Convert.ToInt32(s);
                        languageDetail.LanguageId = id;
                        languageDetail.PersonId = person.PersonId;
                        db.LanguageDetails.Add(languageDetail);
                        db.SaveChanges();
                        s = "";
                        continue;
                    }
                    s += i;
                }
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var l in lang)
                {
                    personInfo.Languages.Add(new Language { LanguageId = l.LanguageId, LanguageName = l.LanguageName, IsSeleted = false });
                }
                ViewBag.CityId = new SelectList(db.Cities, "CityId", "CityName", personInfo.CityId);
                ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", personInfo.CountryId);
                return View(personInfo);
            }
            
        }

        public ActionResult Edit(int? id)
        {
            PersonInfo personInfo = db.PersonInfos.Find(id);

            ViewBag.CityId = new SelectList(db.Cities, "CityId", "CityName", personInfo.CityId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", personInfo.CountryId);

            List<Language> lang = new List<Language>();
            List<Language> list = new List<Language>();
           
            lang = db.Languages.ToList();
            int idd = 0;
            foreach (var l in lang)
            {
                idd = l.LanguageId;
                var nn = personInfo.LanguageDetails.Select(x => x.LanguageId).ToList();//.Find(l.LanguageId);
               
                if(nn.Contains(idd))
                {
                    list.Add(new Language { LanguageId = l.LanguageId, LanguageName = l.LanguageName, IsSeleted = true });
                }
                else
                {
                    list.Add(new Language { LanguageId = l.LanguageId, LanguageName = l.LanguageName, IsSeleted = false });
                }
             
            }
            ViewBag.LanguageDetail = list;
            return View(personInfo);
        }
        
        [HttpPost]
        public ActionResult Edit(PersonInfo personInfo, string hobbies, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                if (file != null)
                {
                    fileName = Path.GetFileNameWithoutExtension(file.FileName);
                    string extension = Path.GetExtension(file.FileName);
                    fileName = fileName + "_" + DateTime.Now.ToString("yymmssfff") + extension;
                    string filePath = Path.Combine(Server.MapPath("~/Images"), fileName);
                    file.SaveAs(filePath);
                    personInfo.Resume = fileName;
                }

                db.Entry(personInfo).State = EntityState.Modified;
                db.SaveChanges();

                LanguageDetail languageDetail = new LanguageDetail();
                var langDetail = db.LanguageDetails.Where(x => x.PersonId == personInfo.PersonId).ToList();
                foreach (var d in langDetail)
                {
                    db.LanguageDetails.Remove(d);
                    db.SaveChanges();
                }

                hobbies = hobbies + ",";
                string s = "";
                foreach (var i in hobbies)
                {
                    if (i == ',')
                    {
                        int id = Convert.ToInt32(s);
                        languageDetail.LanguageId = id;
                        languageDetail.PersonId = personInfo.PersonId;
                        db.LanguageDetails.Add(languageDetail);
                        db.SaveChanges();
                        s = "";
                        continue;
                    }
                    s += i;
                }
                return RedirectToAction("Index");
            }
            else
            {
                PersonInfo person = db.PersonInfos.Find(personInfo.PersonId);
                List<Language> lang = new List<Language>();
                List<Language> list = new List<Language>();

                lang = db.Languages.ToList();
                int idd = 0;
                foreach (var l in lang)
                {
                    idd = l.LanguageId;
                    var nn = person.LanguageDetails.Select(x => x.LanguageId).ToList();//.Find(l.LanguageId);

                    if (nn.Contains(idd))
                    {
                        list.Add(new Language { LanguageId = l.LanguageId, LanguageName = l.LanguageName, IsSeleted = true });
                    }
                    else
                    {
                        list.Add(new Language { LanguageId = l.LanguageId, LanguageName = l.LanguageName, IsSeleted = false });
                    }

                }
                ViewBag.LanguageDetail = list;
                ViewBag.CityId = new SelectList(db.Cities, "CityId", "CityName", person.CityId);
                ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", person.CountryId);
                return View(person);
            }
            
        }
        
        public ActionResult Delete(int? id)
        {
            PersonInfo personInfo = db.PersonInfos.Find(id);
            return View(personInfo);
        }
        
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PersonInfo personInfo = db.PersonInfos.Find(id);
            db.PersonInfos.Remove(personInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
    }
}

InterviewOfOneSoftLimited/Views/PersonInfo/Create.cshtml
@model InterviewOfOneSoftLimited.Models.ViewModel.PersonInfoViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Page</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4><span class="glyphicon glyphicon-envelope"></span> Personal Information</h4>
    </div>
    <div class="panel-body">
        <div class="container" style="width:900px">
            @using (Html.BeginForm("Create", "PersonInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CountryId, "Country", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.DropDownList("CountryId", null, "Select Country", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger", id = "CountryMessage" })
                            @*<span id="CountryMessage" class="text-danger"></span>*@
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CityId, "City", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            <select name="CityId" id="CityId" class="form-control" disabled="disabled">
                                <option value="" selected="selected">Select City</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Languages, "Language Skills", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <input type="hidden" id="hobbies" name="hobbies" value="hobbies" />
                        <div class="col-md-10">
                            @foreach (var i in Model.Languages)
                            {
                                <input id="@(i.LanguageId)"
                                       type="checkbox"
                                       value="@i.LanguageId" />
                                @i.LanguageName<span>&nbsp;&nbsp;&nbsp;</span>
                            }
                            <br />
                            @Html.ValidationMessageFor(model => model.Languages, "", new { @class = "text-danger", id = "validationMessage" })
                           
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DateOfBirth, "Date Of Birth", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control datepicker" } })
                            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Resume, htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            <input name="Resume" type="file" accept="image/pdf,doc" class="form-control" />
                            @Html.ValidationMessageFor(model => model.Resume, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <div class="col-md-5 pull-right">
                                <a href="@Url.Action("Index")" class="btn btn-default pull-left">Cancel</a>
                            </div>
                            <div class="col-md-5 pull-right">
                                <input type="submit" value="Save" class="btn btn-success pull-right" id="btnCreate"  />
                            </div>

                        </div>
                    </div>
                </div>
            }

            @*<div>
                    @Html.ActionLink("Back to List", "Index")
                </div>*@
        </div>
    </div>
    <div class="panel-footer"></div>
</div>


<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section Scripts {

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            var sList = [];
            $("#CountryId").change(function () {
                var c = $(this).val();
                if (c == "") {
                    $("#CityId").empty();
                    $("#CityId").append("<option value='' selected='selected'>Select City</option>")
                        .attr("disabled", "disabled");
                    return;
                }
                else {
                    $("#CityId").empty();
                    $.ajax({
                        type: "GET",
                        url: "/PersonInfo/GetEmps?CountryId=" + c,
                        dataType: "json",
                        success: function (result) {
                            // console.log(result);
                            for (var i = 0; i < result.length; i++) {
                                $("#CityId").append("<option value='" + result[i].CityId + "'>" + result[i].CityName + "</option>")
                            }
                        }
                    });
                    $("#CityId").append("<option value='' selected='selected'>select</option>")
                        .removeAttr("disabled");
                }
                console.log(c);
            });
            $(".datepicker").val(" ");
            $(".datepicker").datepicker({
                dateFormat: "dd M yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
            $('input[type=checkbox]').change(function () {
                //var sList = "";
                $('input[type=checkbox]').each(function () {
                    if (this.checked) {
                        sList.push(this.value)
                    }
                });
                $("#hobbies").val(sList);
                console.log(sList);
                sList = [];
            });

            $('#btnCreate').click( function () {
                    var checkedCount = $("input:checked").length;
                    var valid = checkedCount > 0;
                    if (!valid) {
                        $('#validationMessage').html('Select one or more language!');
                    }
                    return valid;
                });
        });
    </script>

}

InterviewOfOneSoftLimited/Views/PersonInfo/Delete.cshtml
@model InterviewOfOneSoftLimited.Models.PersonInfo

@{
    ViewBag.Title = "Delete";
    string nn = "";
}

<h2>Delete Page</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4><span class="glyphicon glyphicon-envelope"></span> Personal Information</h4>
    </div>
    <div class="panel-body">
        <div class="container" style="width:900px">
            <h3>Are you sure you want to delete this?</h3>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @*@Html.DisplayNameFor(model => model.City.CityName)*@
                        City
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.City.CityName)
                    </dd>

                    <dt>
                        Country
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Country.CountryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt>
                        Language Skills
                    </dt>

                    <dd>
                        @*@{ nn = ""; }*@
                        @foreach (var i in Model.LanguageDetails)
                        {
                            nn += i.Language.LanguageName;
                            nn += "  ,";
                        }
                        @nn.Remove(nn.Length - 1, 1)
                    </dd>
                    <dt>
                        Date Of Birth
                    </dt>

                    <dd>
                        @string.Format("{0:dd MMM yyyy}", Model.DateOfBirth)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Resume)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Resume)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color col-md-offset-2 col-md-10">
                        <div class="col-md-5 pull-right">
                            <a href="@Url.Action("Index")" class="btn btn-default pull-left">Cancel</a>
                        </div>
                        <div class="col-md-5 pull-right">
                            <input type="submit" value="Delete" class="btn btn-danger pull-right" />
                        </div>
                        @*<input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")*@
                    </div>
                }
            </div>

        </div>
        </div>
        <div class="panel-footer"></div>
    </div>

InterviewOfOneSoftLimited/Views/PersonInfo/Edit.cshtml
@model InterviewOfOneSoftLimited.Models.PersonInfo

@{
    ViewBag.Title = "Edit";
    //List<Language> nlist = ViewBag.LanguageDetail;
}

<h2>Edit Page</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4><span class="glyphicon glyphicon-envelope"></span> Personal Information</h4>
    </div>
    <div class="panel-body">
        <div class="container" style="width:900px">
            @using (Html.BeginForm("Edit", "PersonInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.PersonId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CountryId, "Country", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CityId, "City", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Language Skills", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <input type="hidden" id="hobbies" name="hobbies" value="hobbies" />
                        <div class="col-md-10">
                            @foreach (var i in ViewBag.LanguageDetail)
                            {
                                <input id="@(i.LanguageId)"
                                       type="checkbox"
                                       value="@i.LanguageId"
                                       checked="@i.IsSeleted" />
                                @i.LanguageName<span>&nbsp;&nbsp;&nbsp;</span>
                            }
                            <div id="validationMessage" class="text-danger"> </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DateOfBirth, "Date Of Birth", htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control datepicker" } })
                            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Resume, htmlAttributes: new { @class = "control-label col-md-2" })<span class="text-danger">*</span>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Resume, new { htmlAttributes = new { @class = "form-control" } })
                            <input name="file" id="newFile" type="file" accept="image/pdf,doc" class="form-control" />
                            <input type="button" id="btnChange" value="Change" class="btn btn-default" />
                            @Html.ValidationMessageFor(model => model.Resume, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <div class="col-md-5 pull-right">
                                <a href="@Url.Action("Index")" class="btn btn-default pull-left">Cancel</a>
                            </div>
                            <div class="col-md-5 pull-right">
                                <input type="submit" value="Save" class="btn btn-success pull-right" id="btnCreate" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="panel-footer"></div>
</div>





<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section Scripts {

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            var sList = [];
            $("#CountryId").change(function () {
                var c = $(this).val();
                if (c == "") {
                    $("#CityId").empty();
                    $("#CityId").append("<option value='' selected='selected'>Select City</option>")
                        .attr("disabled", "disabled");
                    return;
                }
                else {
                    $("#CityId").empty();
                    $.ajax({
                        type: "GET",
                        url: "/PersonInfo/GetEmps?CountryId=" + c,
                        dataType: "json",
                        success: function (result) {
                            // console.log(result);
                            for (var i = 0; i < result.length; i++) {
                                $("#CityId").append("<option value='" + result[i].CityId + "'>" + result[i].CityName + "</option>")
                            }
                        }
                    });
                    $("#CityId").append("<option value='' selected='selected'>select</option>")
                        .removeAttr("disabled");
                }
                console.log(c);
            });
            //$(".datepicker").val(" ");
            $(".datepicker").datepicker({
                dateFormat: "dd M yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
            $('input[type=checkbox]').change(function () {
                sList = [];
                $('input[type=checkbox]').each(function () {
                    if (this.checked) {
                        sList.push(this.value)
                    }
                });
                $("#hobbies").val(sList);
                console.log(sList);
                //sList = [];
            });
            $('#newFile').hide();
            $("#btnChange").click(function () {
                $('#newFile').show();
                $('#Resume').hide();
            });


            $('input[type=checkbox]').each(function () {
                if (this.checked) {
                    sList.push(this.value)
                }

            });
            $("#hobbies").val(sList);
            console.log(sList);
            sList = [];
        });

        $('#btnCreate').click(function () {
            var checkedCount = $("input:checked").length;
            var valid = checkedCount > 0;
            if (!valid) {
                $('#validationMessage').html('Select one or more language!');
            }
            return valid;
        });
    </script>

}